import { db } from "./index";
import { categoriesTable, menuItemsTable } from "./schema";
import { eq } from "drizzle-orm";

async function addMenuItems() {
  console.log("Adding new categories and menu items from Flare by TK menu...");

  // ── Get existing categories ────────────────────────────────────────────────
  const existing = await db.select().from(categoriesTable);
  const existingMap = new Map(existing.map((c) => [c.slug, c]));

  // ── Insert new categories ──────────────────────────────────────────────────
  const newCategories = [
    {
      name: "Potato Mania",
      slug: "potato-mania",
      description: "Crispy golden fries in every style — classic, loaded, curly and waffle",
      imageUrl: "/menu/loaded-fries.png",
      sortOrder: 8,
      isActive: true,
    },
    {
      name: "Lacha Burgers",
      slug: "lacha-burgers",
      description: "Signature burgers topped with crispy lacha onion rings",
      imageUrl: "/menu/lacha-burger.png",
      sortOrder: 9,
      isActive: true,
    },
    {
      name: "Injected Broast",
      slug: "injected-broast",
      description: "Juicy pressure-fried broast chicken injected with secret marinade",
      imageUrl: "/menu/injected-broast-full.png",
      sortOrder: 10,
      isActive: true,
    },
    {
      name: "Pizza",
      slug: "pizza",
      description: "Stone-baked pizzas with bold Pakistani and international flavors",
      imageUrl: "/menu/pizza-peri-peri.png",
      sortOrder: 11,
      isActive: true,
    },
    {
      name: "Sandwich",
      slug: "sandwich",
      description: "Stacked sandwiches loaded with premium fillings",
      imageUrl: "/menu/club-sandwich.png",
      sortOrder: 12,
      isActive: true,
    },
  ];

  const toInsert = newCategories.filter((c) => !existingMap.has(c.slug));
  let insertedCats: typeof existing = [];
  if (toInsert.length > 0) {
    insertedCats = await db.insert(categoriesTable).values(toInsert).returning();
    console.log(`Inserted ${insertedCats.length} new categories`);
  }

  const allCats = await db.select().from(categoriesTable);
  const catMap = new Map(allCats.map((c) => [c.slug, c.id]));

  // ── Insert menu items ──────────────────────────────────────────────────────
  const items = [
    // ── Potato Mania ──────────────────────────────────────────────────────
    {
      name: "French Fries",
      slug: "french-fries",
      description: "Classic golden crispy French fries, perfectly salted and served piping hot",
      categoryId: catMap.get("potato-mania")!,
      price: "350",
      imageUrl: "/menu/french-fries.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["vegetarian", "popular"],
    },
    {
      name: "Fire Season Masala Fries",
      slug: "fire-season-masala-fries",
      description: "Golden fries tossed in fiery masala seasoning with a bold smoky kick",
      categoryId: catMap.get("potato-mania")!,
      price: "350",
      imageUrl: "/menu/masala-fries.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["spicy", "vegetarian", "popular"],
    },
    {
      name: "All Star Loaded Fries",
      slug: "all-star-loaded-fries",
      description: "Fries loaded with melted cheese, jalapeños, beef crumbles and sour cream — the works",
      categoryId: catMap.get("potato-mania")!,
      price: "500",
      originalPrice: "700",
      imageUrl: "/menu/loaded-fries.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["bestseller", "indulgent"],
    },
    {
      name: "Curly Fries",
      slug: "curly-fries",
      description: "Spiral-cut seasoned curly fries, crispy on the outside, fluffy inside",
      categoryId: catMap.get("potato-mania")!,
      price: "390",
      imageUrl: "/menu/curly-fries.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["vegetarian", "popular"],
    },
    {
      name: "Loaded Curly Fries",
      slug: "loaded-curly-fries",
      description: "Curly fries topped with our signature cheese sauce and spicy masala drizzle",
      categoryId: catMap.get("potato-mania")!,
      price: "450",
      originalPrice: "750",
      imageUrl: "/menu/curly-fries.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["indulgent", "popular"],
    },
    {
      name: "Fries Pizza Affair",
      slug: "fries-pizza-affair",
      description: "Crispy fries layered with pizza sauce, mozzarella and your favourite pizza toppings",
      categoryId: catMap.get("potato-mania")!,
      price: "500",
      originalPrice: "700",
      imageUrl: "/menu/fries-pizza-affair.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["unique", "indulgent"],
    },
    {
      name: "Waffle Fries",
      slug: "waffle-fries",
      description: "Lattice-cut waffle fries, extra crispy with maximum dipping surface",
      categoryId: catMap.get("potato-mania")!,
      price: "450",
      imageUrl: "/menu/waffle-fries.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["vegetarian"],
    },

    // ── Burgers (new items) ────────────────────────────────────────────────
    {
      name: "Mazaydawr Beef Smash Burger",
      slug: "mazaydawr-beef-smash-burger",
      description: "Thin-smashed beef patty with caramelized crust, American cheese and secret sauce — includes fries. Double available.",
      categoryId: catMap.get("burgers")!,
      price: "700",
      imageUrl: "/menu/smash-burger.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["beef", "bestseller", "popular"],
    },
    {
      name: "The OG Zinger Burger",
      slug: "og-zinger-burger",
      description: "The original golden crispy fried chicken zinger fillet with lettuce, mayo and pickles in a toasted bun",
      categoryId: catMap.get("burgers")!,
      price: "400",
      imageUrl: "/menu/zinger-burger.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "popular"],
    },
    {
      name: "The OG Mighty Burger",
      slug: "og-mighty-burger",
      description: "A mighty stack with double zinger patties, hash brown, cheese and coleslaw — bigger, bolder, better",
      categoryId: catMap.get("burgers")!,
      price: "650",
      imageUrl: "/menu/zinger-burger.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["chicken", "premium", "bestseller"],
    },
    {
      name: "Flamed Kissed Grilled Burger",
      slug: "flamed-kissed-grilled-burger",
      description: "Flame-grilled beef patty with visible char marks, fresh veggies and smoky barbecue sauce",
      categoryId: catMap.get("burgers")!,
      price: "700",
      imageUrl: "/menu/grilled-burger.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["beef", "grilled"],
    },
    {
      name: "Long OG Zinger Burger",
      slug: "long-og-zinger-burger",
      description: "Extra-long crispy zinger chicken fillet burger with our signature sauces and fresh toppings",
      categoryId: catMap.get("burgers")!,
      price: "450",
      imageUrl: "/menu/zinger-burger.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken"],
    },
    {
      name: "Classic Chapli Burger",
      slug: "classic-chapli-burger",
      description: "Hand-pressed spiced beef chapli kebab patty in a soft bun with tomatoes and green chutney",
      categoryId: catMap.get("burgers")!,
      price: "450",
      imageUrl: "/menu/chapli-burger.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["beef", "traditional", "popular"],
    },
    {
      name: "Urban Patty Burger",
      slug: "urban-patty-burger",
      description: "Simple, no-fuss juicy beef patty burger with lettuce, tomato and classic sauces",
      categoryId: catMap.get("burgers")!,
      price: "350",
      imageUrl: "/menu/smash-burger.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["beef", "value"],
    },

    // ── Wraps & Rolls (new items) ──────────────────────────────────────────
    {
      name: "Grilled Chicken Roll",
      slug: "grilled-chicken-roll",
      description: "Tender grilled chicken tikka in a soft paratha with onion rings and mint chutney",
      categoryId: catMap.get("wraps-rolls")!,
      price: "550",
      imageUrl: "/menu/chicken-roll.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["chicken", "popular"],
    },
    {
      name: "Peri Peri Roll",
      slug: "peri-peri-roll",
      description: "Fiery peri peri marinated grilled chicken in a paratha with coleslaw and hot sauce",
      categoryId: catMap.get("wraps-rolls")!,
      price: "500",
      imageUrl: "/menu/peri-peri-roll.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "spicy"],
    },
    {
      name: "Zinger Roll",
      slug: "zinger-roll",
      description: "Crispy zinger chicken fillet rolled in a soft paratha with mayo and fresh veggies",
      categoryId: catMap.get("wraps-rolls")!,
      price: "600",
      imageUrl: "/menu/chicken-roll.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "popular"],
    },
    {
      name: "Malai Boti Roll",
      slug: "malai-boti-roll",
      description: "Creamy malai-marinated chicken boti pieces wrapped in soft paratha with onions and green chutney",
      categoryId: catMap.get("wraps-rolls")!,
      price: "600",
      imageUrl: "/menu/malai-boti-roll.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["chicken", "creamy", "bestseller"],
    },
    {
      name: "Cruncy Wrap",
      slug: "cruncy-wrap",
      description: "Crispy chicken strip wrap with crunchy lettuce, cheese and our signature crunch sauce",
      categoryId: catMap.get("wraps-rolls")!,
      price: "600",
      imageUrl: "/menu/beef-wrap.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "crunchy"],
    },
    {
      name: "Turkish Wrap",
      slug: "turkish-wrap",
      description: "Turkish-style döner wrap with seasoned meat, garlic sauce, fresh veggies and fries inside",
      categoryId: catMap.get("wraps-rolls")!,
      price: "600",
      imageUrl: "/menu/beef-wrap.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["popular"],
    },
    {
      name: "Beef Wrap",
      slug: "beef-wrap",
      description: "Premium beef strips, caramelized onions, peppers and smoky BBQ sauce in a flour tortilla",
      categoryId: catMap.get("wraps-rolls")!,
      price: "990",
      imageUrl: "/menu/beef-wrap.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["beef", "premium"],
    },
    {
      name: "Tortilla Wrap",
      slug: "tortilla-wrap",
      description: "Grilled chicken or beef in a soft flour tortilla with fresh salad and signature sauces",
      categoryId: catMap.get("wraps-rolls")!,
      price: "700",
      imageUrl: "/menu/beef-wrap.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["popular"],
    },

    // ── Lacha Burgers ─────────────────────────────────────────────────────
    {
      name: "Lacha Grilled Chicken",
      slug: "lacha-grilled-chicken",
      description: "Flame-grilled chicken burger crowned with crispy lacha onion rings, garlic aioli and fresh greens",
      categoryId: catMap.get("lacha-burgers")!,
      price: "700",
      imageUrl: "/menu/lacha-burger.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["chicken", "popular", "bestseller"],
    },
    {
      name: "Smash Lacha Beef",
      slug: "smash-lacha-beef",
      description: "Double smash beef patty burger with a tower of crispy lacha onion rings and melted cheese",
      categoryId: catMap.get("lacha-burgers")!,
      price: "750",
      imageUrl: "/menu/lacha-burger.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["beef", "bestseller"],
    },
    {
      name: "Lacha Behari",
      slug: "lacha-behari",
      description: "Spiced behari kebab patty burger topped with crispy lacha onions, raita and fresh mint",
      categoryId: catMap.get("lacha-burgers")!,
      price: "750",
      imageUrl: "/menu/lacha-burger.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["beef", "traditional"],
    },

    // ── Injected Broast ───────────────────────────────────────────────────
    {
      name: "Injected Broast Full",
      slug: "injected-broast-full",
      description: "Whole chicken pressure-fried to crispy perfection, injected with our secret spice marinade for max juiciness",
      categoryId: catMap.get("injected-broast")!,
      price: "2300",
      imageUrl: "/menu/injected-broast-full.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["chicken", "sharing", "premium", "bestseller"],
    },
    {
      name: "Injected Broast Half",
      slug: "injected-broast-half",
      description: "Half chicken broast — crispy skin, juicy inside, injected with bold marinade. Perfect for two.",
      categoryId: catMap.get("injected-broast")!,
      price: "1250",
      imageUrl: "/menu/injected-broast-half.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["chicken", "popular"],
    },
    {
      name: "Injected Broast Quarter",
      slug: "injected-broast-quarter",
      description: "Quarter piece of our signature injected broast — golden crispy skin with a succulent interior",
      categoryId: catMap.get("injected-broast")!,
      price: "650",
      imageUrl: "/menu/injected-broast-quarter.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "popular"],
    },

    // ── Pizza ─────────────────────────────────────────────────────────────
    {
      name: "Extreme Peri Peri",
      slug: "extreme-peri-peri-pizza",
      description: "Bold peri peri sauce base with flame-grilled chicken, bell peppers and chili flakes. Medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "1500",
      originalPrice: "2200",
      imageUrl: "/menu/pizza-peri-peri.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["spicy", "chicken", "bestseller"],
    },
    {
      name: "Extreme Malai Boti",
      slug: "extreme-malai-boti-pizza",
      description: "Creamy white malai sauce, tender boti chicken pieces, caramelized onions and mozzarella. Medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "1500",
      originalPrice: "2200",
      imageUrl: "/menu/pizza-malai-boti.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["chicken", "creamy", "bestseller"],
    },
    {
      name: "Flare by TK Special (Crown Crust)",
      slug: "flare-tk-special-crown-crust",
      description: "Our signature pizza — malai boti topping on a crown crust stuffed with mini kebabs. The showstopper. Medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "1550",
      originalPrice: "2350",
      imageUrl: "/menu/pizza-kabab-crust.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["signature", "premium", "bestseller"],
    },
    {
      name: "Chicken Tikka Pizza",
      slug: "chicken-tikka-pizza",
      description: "Tangy tikka marinated chicken, onions, peppers and mozzarella on classic tomato base. Small, medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "700",
      originalPrice: "1650",
      imageUrl: "/menu/pizza-chicken-tikka.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "popular"],
    },
    {
      name: "Chicken Fajita Pizza",
      slug: "chicken-fajita-pizza",
      description: "Grilled fajita chicken strips with sautéed peppers, onions and smoky fajita sauce. Small, medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "700",
      originalPrice: "1650",
      imageUrl: "/menu/pizza-bbq.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "popular"],
    },
    {
      name: "BBQ Pizza",
      slug: "bbq-pizza",
      description: "Smoky BBQ sauce, grilled chicken, crispy onions and melted mozzarella. Small, medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "700",
      originalPrice: "1650",
      imageUrl: "/menu/pizza-bbq.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "popular"],
    },
    {
      name: "Kabab Crust Pizza",
      slug: "kabab-crust-pizza",
      description: "Spiced seekh kabab stuffed in the crust, loaded topping of your choice. A unique Flare creation.",
      categoryId: catMap.get("pizza")!,
      price: "1350",
      originalPrice: "1990",
      imageUrl: "/menu/pizza-kabab-crust.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["unique", "beef", "premium"],
    },
    {
      name: "Nawabi Pizza",
      slug: "nawabi-pizza",
      description: "Royal Nawabi-style pizza with rich creamy chicken, saffron hints and premium toppings. Small, medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "700",
      originalPrice: "1650",
      imageUrl: "/menu/pizza-malai-boti.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "premium"],
    },
    {
      name: "Cheese Pizza",
      slug: "cheese-pizza",
      description: "Pure cheese lover's dream — layers of mozzarella on classic tomato sauce, simple and perfect. Small, medium or large.",
      categoryId: catMap.get("pizza")!,
      price: "600",
      originalPrice: "1500",
      imageUrl: "/menu/pizza-chicken-tikka.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["vegetarian", "popular"],
    },

    // ── Sandwich ──────────────────────────────────────────────────────────
    {
      name: "404 Sando",
      slug: "404-sando",
      description: "The sandwich that can't be found anywhere else — a stacked monster of premium fillings you have to try",
      categoryId: catMap.get("sandwich")!,
      price: "750",
      imageUrl: "/menu/sando-404.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["signature", "popular", "bestseller"],
    },
    {
      name: "Club Sandwich",
      slug: "club-sandwich",
      description: "Triple-decker classic club with grilled chicken, egg, lettuce, tomato and mayo on toasted bread",
      categoryId: catMap.get("sandwich")!,
      price: "700",
      imageUrl: "/menu/club-sandwich.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "classic"],
    },
    {
      name: "Grilled Sandwich",
      slug: "grilled-sandwich",
      description: "Golden grilled sandwich with chicken, cheese and vegetables, pressed to perfection",
      categoryId: catMap.get("sandwich")!,
      price: "650",
      imageUrl: "/menu/grilled-sandwich.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken", "popular"],
    },
    {
      name: "Smash Beef Sandwich",
      slug: "smash-beef-sandwich",
      description: "Smashed beef patty on toasted brioche with caramelized onions, cheese and special sauce",
      categoryId: catMap.get("sandwich")!,
      price: "990",
      imageUrl: "/menu/smash-beef-sandwich.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["beef", "premium", "popular"],
    },
    {
      name: "Panini Sandwich",
      slug: "panini-sandwich",
      description: "Italian-style pressed panini with grilled chicken, melted mozzarella and pesto mayo",
      categoryId: catMap.get("sandwich")!,
      price: "650",
      imageUrl: "/menu/panini-sandwich.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["chicken"],
    },

    // ── Drinks (new items) ────────────────────────────────────────────────
    {
      name: "Sky Sip (Medium)",
      slug: "sky-sip-medium",
      description: "Flare's signature house drink — a refreshing blend of flavors. Ask our team for today's special.",
      categoryId: catMap.get("drinks")!,
      price: "350",
      imageUrl: "/menu/sky-sip.png",
      isAvailable: true,
      isFeatured: true,
      tags: ["cold", "signature", "popular"],
    },
    {
      name: "Sky Sip (Large)",
      slug: "sky-sip-large",
      description: "Large serving of Flare's signature house drink — go big with the full pour.",
      categoryId: catMap.get("drinks")!,
      price: "500",
      imageUrl: "/menu/sky-sip.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["cold", "signature"],
    },
    {
      name: "Soft Drink Tin",
      slug: "soft-drink-tin",
      description: "Chilled 330ml can — Pepsi, 7UP, Mirinda or Mountain Dew",
      categoryId: catMap.get("drinks")!,
      price: "150",
      imageUrl: "/menu/soft-drink-tin.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["cold"],
    },
    {
      name: "Regular Drink",
      slug: "regular-drink",
      description: "Fresh house drink served chilled — ask for today's options",
      categoryId: catMap.get("drinks")!,
      price: "120",
      imageUrl: "/menu/sky-sip.png",
      isAvailable: true,
      isFeatured: false,
      tags: ["cold"],
    },
  ];

  // Filter out slugs that already exist
  const existingItems = await db.select({ slug: menuItemsTable.slug }).from(menuItemsTable);
  const existingSlugs = new Set(existingItems.map((i) => i.slug));
  const newItems = items.filter((i) => !existingSlugs.has(i.slug));

  if (newItems.length === 0) {
    console.log("All items already exist — nothing to insert.");
    process.exit(0);
  }

  const inserted = await db.insert(menuItemsTable).values(newItems).returning();
  console.log(`✅ Inserted ${inserted.length} new menu items`);
  console.log("Done!");
  process.exit(0);
}

addMenuItems().catch((err) => {
  console.error("Error:", err);
  process.exit(1);
});
